### ISSUE TITLE
Update PULP cluster test suite with the Astral one.

### ISSUE THREAD

**Issue by yvantor** [pulp-platform/astral#28]
PULP cluster sw.mk still relies on the carfield cluster test-suite (see [here](https://github.com/pulp-platform/astral/blob/astral/sw/tests/bare-metal/pulpd/sw.mk#L15)). Needs to be updated for using the Astral test-suite, and the CI has to be aligned accordingly.

**Comment by LuigiGhionda** [comment]
This is the related PR for the non-free: https://iis-git.ee.ethz.ch/astral/astral-nonfree/-/merge_requests/14.

Are we interested in adding fault injection tests to this level as well? I see that in Carfield's case they were not present.

**Comment by yvantor** [comment]
In Carfield we had not fault injection test case. We can add all the testcases present under `astral/` folder of the regression tests!

**Comment by LuigiGhionda** [comment]
With the addition of softex test now all the tests in the `astral/` folder are present.
